server:
  port: ${EUREKA_PORT:8761}
  shutdown: graceful

spring:
  application:
    name: discovery-server
  security:
    user:
      name: ${EUREKA_USERNAME:eureka}
      password: ${EUREKA_PASSWORD:change-eureka-password}
      roles: SYSTEM

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
