import { useState } from 'react';
import { Alert, Button, Card, CardContent, Divider, Grid2, Stack, TextField, Typography } from '@mui/material';
import { toast } from 'react-toastify';
import PageTitle from '../components/PageTitle';
import StatusChip from '../components/StatusChip';
import api, { apiMessage } from '../api/client';

export default function ReceptionPage() {
  const [token, setToken] = useState(''); const [location, setLocation] = useState('Main Gate');
  const [verification, setVerification] = useState(null); const [visitId, setVisitId] = useState(''); const [lastVisit, setLastVisit] = useState(null);
  const verify = async () => { try { const { data } = await api.post('/api/v1/reception/passes/verify', { token: token.trim(), location }); setVerification(data); data.valid ? toast.success('Pass is valid') : toast.warning(`Pass: ${data.result}`); } catch (e) { toast.error(apiMessage(e, 'Verification failed')); } };
  const checkIn = async () => { try { const { data } = await api.post('/api/v1/reception/visits/check-in', { token: token.trim(), location }); setLastVisit(data); setVisitId(data.id); setVerification(null); toast.success(`${data.visitorName} checked in`); } catch (e) { toast.error(apiMessage(e, 'Check-in failed')); } };
  const checkOut = async () => { try { const { data } = await api.post(`/api/v1/reception/visits/${visitId}/check-out`); setLastVisit(data); toast.success(`${data.visitorName} checked out`); } catch (e) { toast.error(apiMessage(e, 'Check-out failed')); } };
  return <><PageTitle title="Reception gate desk" subtitle="Verify a FastPass, check visitors in, and complete their visit." /><Grid2 container spacing={3}><Grid2 size={{ xs: 12, md: 7 }}><Card><CardContent sx={{ p: 3 }}><Typography variant="h6">Scan or paste QR token</Typography><TextField fullWidth multiline minRows={4} label="Secure QR token" value={token} onChange={(e) => { setToken(e.target.value); setVerification(null); }} sx={{ mt: 2 }} /><TextField fullWidth label="Gate or location" value={location} onChange={(e) => setLocation(e.target.value)} sx={{ mt: 2 }} /><Button fullWidth variant="contained" size="large" disabled={!token.trim()} onClick={verify} sx={{ mt: 2 }}>Verify FastPass</Button>{verification && <Alert severity={verification.valid ? 'success' : 'error'} sx={{ mt: 2 }}>{verification.valid ? `${verification.visitorName} is cleared to check in.` : `Pass cannot be used: ${verification.result}`}</Alert>}{verification?.valid && <Card variant="outlined" sx={{ mt: 2 }}><CardContent><Stack direction="row" justifyContent="space-between"><Typography variant="h6">{verification.visitorName}</Typography><StatusChip value={verification.status} /></Stack><Typography>Host: {verification.hostName}</Typography><Typography>Purpose: {verification.purpose}</Typography><Typography>Scheduled: {new Date(verification.scheduledAt).toLocaleString()}</Typography><Button fullWidth color="success" variant="contained" onClick={checkIn} sx={{ mt: 2 }}>Check visitor in</Button></CardContent></Card>}</CardContent></Card></Grid2>
    <Grid2 size={{ xs: 12, md: 5 }}><Card><CardContent sx={{ p: 3 }}><Typography variant="h6">Check out visitor</Typography><Typography color="text.secondary">Enter the visit ID shown after check-in.</Typography><TextField fullWidth label="Visit ID" value={visitId} onChange={(e) => setVisitId(e.target.value)} sx={{ mt: 2 }} /><Button fullWidth variant="outlined" disabled={!visitId} onClick={checkOut} sx={{ mt: 2 }}>Complete check-out</Button>{lastVisit && <><Divider sx={{ my: 2 }} /><Typography fontWeight={700}>{lastVisit.visitorName}</Typography><StatusChip value={lastVisit.status} /></>}</CardContent></Card></Grid2></Grid2>
  </>;
}
