eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:change-eureka-password}@localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  forward-headers-strategy: framework
